mysql:
  user: "grom"
  password: "123456"
  database: "wordpress"
  persistence:
    enabled: true
    size: 10Gi

wordpress:
  persistence:
    enabled: true
    size: 10Gi
  replicaCount: 1

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  host: wordpress.example.com
