Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/bionic64"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.hostname = "server.local"
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/bionic64"
    client.vm.network "private_network", ip: "192.168.56.11"
    client.vm.hostname = "client.local"
    client.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end

