name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    # Проверка кода из репозитория
    - name: Checkout source code
      uses: actions/checkout@v3

    # Установка JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    # Установка Maven 3.9.9 с помощью s4u/maven-action
    - name: Setup Maven
      uses: s4u/maven-action@v2
      with:
        maven-version: '3.9.9'

    # Проверка версии Maven
    - name: Print Maven Version
      run: mvn -v


    # Сборка и тестирование с Maven
    - name: Build and Test
      run: mvn clean verify -Denforcer.skip=true

    # Сохранение артефакта сборки
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-app-jar
        path: target/*.jar

    # Вход в GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Определение имени образа в нижнем регистре
    - name: Define Docker Image Name
      run: echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/hello-world:latest" >> $GITHUB_ENV

    # Преобраование имени образа в нижний регистр
    - name: Convert Image Name to Lowercase
      run: echo "IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    # Сборка Docker-обраа
    - name: Build Docker Image
      run: docker build -t "$IMAGE_NAME_LOWER" .

    # Публикация Docker-обраа в GitHub Container Registry
    - name: Push Docker Image
      run: docker push "$IMAGE_NAME_LOWER"
