---
- name: Установка MySQL на Ubuntu
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client
  when: ansible_facts['os_family'] == "Debian"

- name: Установка MySQL на CentOS
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-server
    - mariadb
  when: ansible_facts['os_family'] == "RedHat"

- name: Запуск и включение MySQL
  service:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: yes

- name: Установка пароля root для MySQL
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - '::1'

- name: Создание базы данных для WordPress
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present

- name: Создание пользователя базы данных для WordPress
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
